@url = http://localhost:7999/schedule

GET {{url}}
Accept: text/html
###

GET {{url}}
Accept: application/json
###

GET {{url}}?last-known-id=267805
Accept: application/json
###

GET {{url}}
Accept: text/event-stream
###

GET {{url}}
Accept: text/whateverelse